# -*- coding: utf-8 -*-
"""ai_text_to_image_generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oKtI6ue8SNy-NBESklC7y_jwRJXhQsNg
"""

# -- coding: utf-8 --
"""AI Text-to-Image GeneraStableDiffuseor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_opl89r3Z6wPEVWFBKARDbbijLDBqF16
"""



import torch
from diffusers import StableDiffusionPipeline
import matplotlib.pyplot as plt

from huggingface_hub import login
login("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")

pipe = StableDiffusionPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    torch_dtype=torch.float16,
    use_safetensors =True).to("cuda")

user_prompt = input("Enter your image prompt: ")
image = pipe(user_prompt).images[0]
# Display the generated image
plt.imshow(image)
plt.axis('off')
plt.title('Generated Image')
plt.show()

"""create interface streamlite

"""

!pip install diffusers transformers accelerate --upgrade
!pip install safetensors